apiVersion: v1
kind: Secret
metadata: 
  name: mongodb-secret
type: Opaque 
data: 
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=

#default key-value pair type for k8s is Opaque
#data will be base64 encoded here and not the plain text
#in linux CLI type 'echo -n [your-username] | base64' (same for the password)
#the base64 text you get, you provide that as a data here