apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer #this is an external service
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30000 #at this port the external service Ip address will be listening to